# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xJLie6weNrcOrIeT3fDn7Yi9cyWLMyCw
"""

import streamlit as st
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
from streamlit_folium import st_folium
import folium

# --- Cargar datos ---
bo_atr = gpd.read_file("data/bo_atr.geojson")
bo_atr2 = gpd.read_file("data/bo_atr2.geojson")
bo_act = gpd.read_file("data/bo_act.geojson")
bo_gr = gpd.read_file("data/bo_gr.geojson")
bo_map = "mapa_turismo_bolivia.html"  # Mapa exportado

# --- Configuración de la app ---
st.set_page_config(page_title="Dashboard Turístico Bolivia", layout="wide")
st.title("📊 Dashboard Turístico Interactivo de Bolivia")

st.markdown("Explora los atractivos y actividades turísticas por tipo, región y categoría. Filtra, visualiza y analiza los datos geoespaciales de Bolivia.")

# --- Filtros ---
st.sidebar.header("🎛️ Filtros")

tipos_vocacion = bo_atr['vocaciÓn'].dropna().unique()
vocacion_seleccionada = st.sidebar.multiselect("Tipo de vocación turística", tipos_vocacion, default=tipos_vocacion)

tipos_actividad = bo_act['tipo_activ'].dropna().unique()
actividad_seleccionada = st.sidebar.multiselect("Tipo de actividad turística", tipos_actividad, default=tipos_actividad)

# --- Filtrar datos ---
atr_filtrados = bo_atr[bo_atr['vocaciÓn'].isin(vocacion_seleccionada)]
act_filtradas = bo_act[bo_act['tipo_activ'].isin(actividad_seleccionada)]

# --- Gráfico comparativo por región ---
st.subheader("📍 Atractivos turísticos por región")
bo_atr_reg = gpd.sjoin(atr_filtrados, bo_gr, how='left', predicate='intersects')
conteo_por_region = bo_atr_reg['region'].value_counts()

fig, ax = plt.subplots()
conteo_por_region.plot(kind='barh', ax=ax, color='skyblue', edgecolor='black')
ax.set_xlabel("Cantidad de atractivos")
ax.set_ylabel("Región")
st.pyplot(fig)

# --- Visualizar mapa interactivo ---
st.subheader("🗺️ Mapa interactivo")
st.markdown("Visualiza el mapa completo con capas geoespaciales y clusters turísticos.")
st_folium(bo_map, width=900, height=600)